create table TMDL_API_MTDAT_APPL (
  API_MTDAT_APPL_ID             char(36)        primary key,
  APPL_ID                       varchar2(20)    not null,
  API_CLNT_ID                   varchar2(128)   not null,
  OBJ_STAT_TXT                  varchar2(255),
  OBJ_STAT_DT                   date,
  OBJ_STAT_UPDT_BY_ID           varchar2(64),
  OBJ_STAT_UPDT_BY_ID_TYPE_NM   varchar2(128),
  OBJ_STAT_UPDT_BY_NM           varchar2(128),
  OBJ_STAT_UPDT_EMAIL_ADDR_TXT  varchar2(255),
  OBJ_STAT_CMNT_TXT             varchar2(1024),
  LD_IND                        char(1),
  LD_DTTM                       timestamp(6),
  API_MTDAT_APPL_LFCYC_STAT_TXT varchar2(255),
  RUN_ID                        varchar2(32)    not null,
  CRTE_DTTM                     timestamp(6) default sysdate,
  CRTE_BY_ID                    varchar2(20),
  UPDT_DTTM                     timestamp(6),
  UPDT_BY_ID                    varchar2(20),
  ERR_FLG_IND                   char(1),
  ERR_TXT                       varchar2(255)
);

create table TMDL_API_TCNCL_MTDAT_DSET (
  API_MTDAT_DSET_ID             char(36)        primary key ,
  API_MTDAT_APPL_ID             char(36)        not null,
  MSG_TYPE_NUM                  number(38,0)    not null,
  DAT_SRC_INGST_SYS_NM          varchar2(64)    not null,
  DAT_STOR_NM                   varchar2(255)   not null,
  PHYS_SVR_NM                   varchar2(255)   not null,
  DAT_STOR_LOC_NM               varchar2(500),
  DAT_STOR_PLTFM_NM             varchar2(128),
  URL                           varchar2(255),
  APPL_SYS_TYPE_CD              varchar2(10),
  APPL_SYS_TYPE_NM              varchar2(128),
  DAT_STOR_PLTFM_CD             varchar2(50),
  DAT_STOR_DESC                 varchar2(4000),
  DAT_STOR_CRTE_DT              date,
  DAT_SET_NM                    varchar2(255)   not null,
  DAT_SET_DESC                  varchar2(4000),
  DAT_SET_TYPE_NM               varchar2(128),
  DAT_SET_CRTE_DT               date,
  PRTN_COL_NM                   varchar2(128),
  USR_GRP_TYPE_TXT              varchar2(500),
  USR_GRP_TXT                   varchar2(500),
  REPLICA_CLUSTERS_TXT          varchar2(500),
  LD_IND                        char(1),
  LD_DTTM                       timestamp(6),
  API_MTDAT_DSET_LFCYC_STAT_TXT varchar2(255),
  RUN_ID                        varchar2(32)    not null,
  CRTE_DTTM                     timestamp(6) default sysdate,
  CRTE_BY_ID                    varchar2(20),
  UPDT_DTTM                     timestamp(6),
  UPDT_BY_ID                    varchar2(20),
  ERR_FLG_IND                   char(1),
  ERR_TXT                       varchar2(255)
);

create table TMDL_API_TCNCL_MTDAT_PDE (
  API_MTDAT_PDE_ID              char(36)      primary key ,
  API_MTDAT_DSET_ID             char(36)      not null,
  MSG_TYPE_NUM                  number(38, 0),
  PHYS_DAT_ELEM_NM              varchar2(255) not null,
  PHYS_DAT_ELEM_DAT_TYPE_NM     varchar2(255),
  PHYS_DAT_ELEM_DESC            varchar2(4000),
  PHYS_DAT_ELEM_FMT             varchar2(255),
  PHYS_DAT_ELEM_LEN             number(38, 0),
  PRCSN_DGT_NUM                 number(38, 0),
  SCALE_DGT_NUM                 number(38, 0),
  NULL_IND                      char(1),
  ENCRYPT_IND                   char(1),
  PRIM_KY_IND                   char(1),
  PRIV_IND                      char(1),
  PII_IND                       char(1),
  PII_TXT                       varchar2(255),
  EXT_SEC_CLASS_IND             char(1),
  EXT_SEC_CLASS_TXT             varchar2(255),
  SEC_LVL_NM                    varchar2(255),
  BUS_ELEM_NM                   varchar2(255),
  ST_MTDAT_IND                  char(1),
  LD_IND                        char(1),
  LD_DTTM                       timestamp(6),
  API_MTDAT_DSET_LFCYC_STAT_TXT varchar2(255),
  RUN_ID                        varchar2(32)  not null,
  CRTE_DTTM                     timestamp(6) default sysdate,
  CRTE_BY_ID                    varchar2(20),
  UPDT_DTTM                     timestamp(6),
  UPDT_BY_ID                    varchar2(20),
  ERR_FLG_IND                   char(1),
  ERR_TXT                       varchar2(255)
);